care_home_app/accounts/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('view/', views.view_account, name='view'),
    path('edit/', views.edit_account, name='edit'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/care_home_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('pdf-filler/', include('pdf_filler.urls', namespace='pdf_filler')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_home_app/profiles/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('create-client-profile/',
         views.create_client_profile,
         name='create_client_profile'),
    path('edit-client-profile/<pk>/',
         views.edit_client_profile,
         name='edit_client_profile'),
    path('client-profile/<pk>/',
         views.view_client_profile,
         name='client_profile'),
    path('client-list/', views.view_client_list, name='client_list'),
    path('create-doctor-profile/',
         views.create_doctor_profile,
         name='create_doctor_profile'),
    path('edit-doctor-profile/<pk>/',
         views.edit_doctor_profile,
         name='edit_doctor_profile'),
    path('doctor-profile/<pk>/',
         views.view_doctor_profile,
         name='doctor_profile'),
    path('doctor-list/', views.view_doctor_list, name='doctor_list'),
    path('create-medication/',
         views.create_medication,
         name='create_medication'),
    path('edit-medication-profile/<pk>/',
         views.edit_medication_profile,
         name='edit_medication_profile'),
    path('medication-profile/<pk>/',
         views.view_medication_profile,
         name='medication_profile'),
    path('medication-list/', views.view_medication_list, name='medication_list'),
    path('create-prescription/',
         views.create_prescription,
         name='create_prescription'),
    path('edit-prescription-profile/<pk>/',
      views.edit_prescription_profile,
      name='edit_prescription_profile'),
    path('prescription-profile/<pk>/',
         views.view_prescription_profile,
         name='prescription_profile'),
    path('create-new-bodyweight/<client_id>',
      views.create_new_bodyweight,
      name='create_new_bodyweight'),
      path('bodyweight-list/<client_id>', views.view_bodyweight_list, name='bodyweight_list'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <h1>Ryan Family Care Home</h1>
{% endblock %}

care_home_app/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <!-- Navbar -->
  <navbar>
    <ul class="nav-list">
      <a class="nav-item" href="{% url 'index' %}"><img src="{% static 'icons/icons8-home.svg' %}"></a>
      {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'profiles:client_list' %}">Clients</a></li>
        <li class="nav-item float-r"><a href="{% url 'accounts:view' %}">My Account</a></li>
        <li class="nav-item"><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
        <li class="nav-item float-r"><a href="{% url 'accounts:login' %}">Login</a></li>
      {% endif %}
    </ul>
  </navbar>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>