care_home_app/accounts/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('view/', views.view_account, name='view'),
    path('edit/', views.edit_account, name='edit'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/care_home_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('pdf-filler/', include('pdf_filler.urls', namespace='pdf_filler')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_home_app/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=User)
def create_user_account(sender, instance, created, **kwargs):
    if created:
        UserAccount.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_account(sender, instance, **kwargs):
    instance.useraccount.save()


class UserAccount(models.Model):
    """A user profile model that extends the built-in user model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=14, blank=True)

care_home_app/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


class UserUpdateForm(forms.ModelForm):
    """Form to allow users to update their user information"""
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )


class UserAccountUpdateForm(forms.ModelForm):
    """Form to allow users to update account information."""

    class Meta:
        model = models.UserAccount
        fields = (
            'dob',
            'address',
            'phone',
        )

care_home_app/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       UserChangeForm)
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .import forms


def sign_in(request):
    """Process the user login request."""
    form = AuthenticationForm
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    # messages.success(
                    #     request,
                    #     f"You are now logged in as {user.username}"
                    # )
                    return HttpResponseRedirect(reverse('index'))
                else:
                    # messages.error(
                    #     request,
                    #     "That user account has been disabled"
                    # )
                    pass
            else:
                # message.error(
                #     request,
                #     "The username or password is incorrect"
                # )
                pass
    return render(
        request,
        'accounts/login.html',
        {'form': form}
    )


def sign_out(request):
    """Log the user out of the site."""
    logout(request)
    # messages.success(request, "You've been logged out. Come back soon!")
    return HttpResponseRedirect(reverse('index'))


@login_required
def view_account(request):
    """Display the details of the user's account."""
    user = request.user
    return render(request, 'accounts/view_account.html', {'user': user})


@login_required
def edit_account(request):
    """Edit the details of the user's profile"""
    if request.method == 'POST':
        user_update_form = forms.UserUpdateForm(
            request.POST,
            instance=request.user
        )
        user_account_update_form = forms.UserAccountUpdateForm(
            request.POST,
            instance=request.user.useraccount
        )
        if user_update_form.is_valid() and user_account_update_form.is_valid():
            user_update_form.save()
            user_account_update_form.save()
            # messages.success(request, "Your profile has been updated!")
            return HttpResponseRedirect(reverse('accounts:view'))
    else:
        user_update_form = forms.UserUpdateForm(
            instance=request.user
        )
        user_account_update_form = forms.UserAccountUpdateForm(
            instance=request.user.useraccount
        )
    return render(request,
                  'accounts/edit_account.html',
                  {
        'user_update_form': user_update_form,
        'user_account_update_form': user_account_update_form
    })

care_home_app/accounts/templates/accounts/edit_account.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}Edit Account{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ user_update_form.as_p }}
    {{ user_account_update_form.as_p }}
    <button id="saveBtn" type="submit">Save</button>
  </form>
</div>
{% endblock %}

care_home_app/accounts/templates/accounts/edit_profile.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="saveBtn" type="submit">Register</button>
  </form>
</div>
{% endblock %}

care_home_app/accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <form method="POST" action="{% url 'accounts:login' %}">
    <div class="form-group">
      {% csrf_token %}
      {{ form }}
    </div>
    <button type="submit">Login</button>
  </form>
{% endblock %}

care_home_app/accounts/templates/accounts/view_account.html
{% extends 'layout.html' %}

{% block title %}My Account{% endblock %}

{% block content %}
  <h1>Account</h1>
  <h2>{% if user.first_name %}{{ user.first_name }}{% endif %} {% if user.last_name %}{{ user.last_name }}{% endif %}</h2>
  {% if user.email %}
  <h3>Email</h3>
  <p>{{ user.email }}</p>
  {% endif %}
  {% if user.useraccount.dob %}
  <h3>DOB</h3>
  <p>{{ user.useraccount.dob }}</p>
  {% endif %}
  {% if user.useraccount.address %}
  <h3>Address</h3>
  <p>{{ user.useraccount.address }}</p>
  {% endif %}
  {% if user.useraccount.phone %}
  <h3>Phone</h3>
  <p>{{ user.useraccount.phone }}</p>
  {% endif %}
  <p><a href="{% url 'accounts:edit' %}">Edit Account</a></p>
{% endblock %}