care_home_app/accounts/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('view/', views.view_account, name='view'),
    path('edit/', views.edit_account, name='edit'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/care_home_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('pdf-filler/', include('pdf_filler.urls', namespace='pdf_filler')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

care_home_app/pdf_filler/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'pdf_filler'
urlpatterns = [
    path('fill-LIC624/<client_pk>', views.fill_LIC624, name='fill_LIC624'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/profiles/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('create-client-profile/',
         views.create_client_profile,
         name='create_client_profile'),
    path('edit-client-profile/<pk>/',
         views.edit_client_profile,
         name='edit_client_profile'),
    path('client-profile/<pk>/',
         views.view_client_profile,
         name='client_profile'),
    path('client-list/', views.view_client_list, name='client_list'),
    path('create-doctor-profile/',
         views.create_doctor_profile,
         name='create_doctor_profile'),
    path('edit-doctor-profile/<pk>/',
         views.edit_doctor_profile,
         name='edit_doctor_profile'),
    path('doctor-profile/<pk>/',
         views.view_doctor_profile,
         name='doctor_profile'),
    path('doctor-list/', views.view_doctor_list, name='doctor_list'),
    path('create-medication/',
         views.create_medication,
         name='create_medication'),
    path('edit-medication-profile/<pk>/',
         views.edit_medication_profile,
         name='edit_medication_profile'),
    path('medication-profile/<pk>/',
         views.view_medication_profile,
         name='medication_profile'),
    path('medication-list/', views.view_medication_list, name='medication_list'),
    path('create-prescription/',
         views.create_prescription,
         name='create_prescription'),
    path('edit-prescription-profile/<pk>/',
      views.edit_prescription_profile,
      name='edit_prescription_profile'),
    path('prescription-profile/<pk>/',
         views.view_prescription_profile,
         name='prescription_profile'),
    path('create-new-bodyweight/<client_id>',
      views.create_new_bodyweight,
      name='create_new_bodyweight'),
      path('bodyweight-list/<client_id>', views.view_bodyweight_list, name='bodyweight_list'),
]
urlpatterns += staticfiles_urlpatterns()

care_home_app/profiles/models.py
from datetime import date
from django.db import models

from thumbnails.fields import ImageField


class Client(models.Model):
    """Personal details for a care home client."""
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    portrait = ImageField(default='images/default.jpeg', resize_source_to='large', upload_to='images')
    sex = models.CharField(max_length=255)
    dob = models.DateField()
    admission_date = models.DateField()
    address = models.CharField(max_length=255)
    doctors = models.ManyToManyField('Doctor', blank=True)
    current_client = models.BooleanField(default=True)
    uci_number = models.IntegerField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def age(self):
        return (date.today().year - self.dob.year - ((
                date.today().month,
                date.today().day) < (self.dob.month, self.dob.day)))

    @property
    def full_name(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'

    @property
    def last_name_first(self):
        return f'{self.last_name}, {self.first_name}'


class Doctor(models.Model):
    """Information for client's doctors."""
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    suffix = models.CharField(max_length=255, blank=True)
    specialty = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.first_name} {self.last_name}, {self.suffix}'


class Medication(models.Model):
    """Medication name and strength."""
    name = models.CharField(max_length=255)
    strength = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name} {self.strength}'


class Prescription(models.Model):
    """Information for client prescriptions."""
    medication = models.ForeignKey('Medication', on_delete=models.PROTECT)
    rx_instructions = models.TextField()
    prescribing_dr = models.ForeignKey('Doctor', on_delete=models.PROTECT)
    prescribed_to = models.ForeignKey('Client', on_delete=models.PROTECT)

    def __str___(self):
        return f'{self.medication}'


class BodyWeight(models.Model):
    client = models.ForeignKey('Client', on_delete=models.PROTECT)
    weight = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.weight}'

care_home_app/profiles/forms.py
from django import forms

from . import models

class ClientCreationForm(forms.ModelForm):
    """Form to add a new client."""

    class Meta:
        model = models.Client
        fields = (
            'first_name',
            'middle_name',
            'last_name',
            'portrait',
            'dob',
            'admission_date',
            'address',
        )


class ClientUpdateForm(forms.ModelForm):
    """Form to update details of a client profile."""

    class Meta:
        model = models.Client
        fields = (
            'portrait',
            'first_name',
            'middle_name',
            'last_name',
            'dob',
            'admission_date',
            'address',
            'doctors',
        )


class DoctorCreationForm(forms.ModelForm):
    """Form to add a new doctor."""

    class Meta:
        model = models.Doctor
        fields = (
            'first_name',
            'last_name',
            'suffix',
            'specialty',
            'address',
            'phone',
        )


class DoctorUpdateForm(forms.ModelForm):
    """Form to update details of a client profile"""

    class Meta:
        model = models.Doctor
        fields = (
            'first_name',
            'last_name',
            'suffix',
            'specialty',
            'address',
            'phone',
        )


class MedicationCreationForm(forms.ModelForm):
    """Form to create a new medication."""

    class Meta:
        model = models.Medication
        fields = (
            'name',
            'strength',
        )


class MedicationUpdateForm(forms.ModelForm):
    """Form to update an existing medication."""

    class Meta:
        model = models.Medication
        fields = (
            'name',
            'strength',
        )


class PrescriptionCreationForm(forms.ModelForm):
    """Form to create a new prescription."""

    class Meta:
        model = models.Prescription
        fields = (
            'medication',
            'rx_instructions',
            'prescribing_dr',
            'prescribed_to',
        )


class PrescriptionUpdateForm(forms.ModelForm):
    """Form to update an existing prescription."""

    class Meta:
        model = models.Prescription
        fields = (
            'medication',
            'rx_instructions',
            'prescribing_dr',
            'prescribed_to',
        )


class NewBodyWeightForm(forms.ModelForm):
    """Create new bodyweight record."""

    class Meta:
        model = models.BodyWeight
        fields = (
            'weight',
        )

care_home_app/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from . import forms
from . import models


###################################################
# Client creation, editing, deleting, and viewing #
###################################################
@login_required
def create_client_profile(request):
    """Create new Client profile."""
    form = forms.ClientCreationForm()
    if request.method == 'POST':
        form = forms.ClientCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    return render(
        request,
        'profiles/create_profile.html',
        {'form': form, 'creation_name': 'Client'})


@login_required
def edit_client_profile(request, pk):
    """Edit Client profile."""
    client = models.Client.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.ClientUpdateForm(
            request.POST,
            request.FILES,
            instance=client
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:client_profile',
                                                args=[client.id]))
    else:
        form = forms.ClientUpdateForm(instance=client)
    return render(
        request,
        'profiles/edit_client_profile.html',
        {'form': form, 'client': client}
        )


@login_required
def view_client_profile(request, pk):
    """Show the details of a client profile."""
    client = get_object_or_404(models.Client, id=pk)
    doctors = models.Doctor.objects.filter(client__pk=pk)
    prescriptions = models.Prescription.objects.filter(prescribed_to=pk)
    try:
        weight = models.BodyWeight.objects.filter(client_id=pk).latest('date')
    except:
        weight = 'Not yet recorded'
    return render(
        request,
        'profiles/view_client_profile.html',
        {'client': client,
         'doctors': doctors,
         'prescriptions': prescriptions,
         'weight': weight}
        )


@login_required
def view_client_list(request):
    """List of all clients."""
    clients = models.Client.objects.filter(current_client=True).order_by('last_name')
    return render(request, 'profiles/client_list.html', {'clients': clients})


###################################################
# Doctor creation, editing, deleting, and viewing #
###################################################
@login_required
def create_doctor_profile(request):
    """Create new Doctor profile."""
    form = forms.DoctorCreationForm()
    if request.method == 'POST':
        form = forms.DoctorCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    return render(
        request,
        'profiles/create_profile.html',
        {'form': form, 'creation_name': 'Doctor'})


@login_required
def edit_doctor_profile(request, pk):
    """Edit a Doctor's profile."""
    doctor = models.Doctor.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.DoctorUpdateForm(
            request.POST,
            instance=doctor
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:doctor_profile',
                                                args=[doctor.id]))
    else:
        form = forms.DoctorUpdateForm(instance=doctor)
    return render(
        request,
        'profiles/edit_profile.html',
        {'form': form, 'edit_name': 'Doctor'}
        )


@login_required
def view_doctor_profile(request, pk):
    """Show the details of a doctor's profile."""
    doctor = get_object_or_404(models.Doctor, id=pk)
    clients = models.Client.objects.filter(doctors__pk=pk)
    return render(
        request,
        'profiles/view_doctor_profile.html',
        {'doctor': doctor, 'clients': clients}
        )


@login_required
def view_doctor_list(request):
    """List of all doctors."""
    doctors = models.Doctor.objects.all()
    return render(request, 'profiles/doctor_list.html', {'doctors': doctors})

#######################################################
# Medication creation, editing, deleting, and viewing #
#######################################################
@login_required
def create_medication(request):
    """Create a new medication profile."""
    form = forms.MedicationCreationForm()
    if request.method == 'POST':
        form = forms.MedicationCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    return render(
        request,
        'profiles/create_profile.html',
        {'form': form, 'creation_name': 'Medication'})


@login_required
def edit_medication_profile(request, pk):
    """Edit a medication profile."""
    medication = models.Medication.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.MedicationUpdateForm(
            request.POST,
            instance=medication
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:medication_profile',
                                                args=[medication.id]))
    else:
        form = forms.MedicationUpdateForm(instance=medication)
    return render(
        request,
        'profiles/edit_profile.html',
        {'form': form, 'edit_name': 'Medication'}
        )


@login_required
def view_medication_profile(request, pk):
    """Show the details of a medication profile."""
    medication = get_object_or_404(models.Medication, id=pk)
    return render(
        request,
        'profiles/view_medication_profile.html',
        {'medication': medication}
        )


@login_required
def view_medication_list(request):
    """List of all medications."""
    medications = models.Medication.objects.all()
    return render(
        request,
        'profiles/medication_list.html',
        {'medications': medications}
        )

#######################################################
# Medication creation, editing, deleting, and viewing #
#######################################################
@login_required
def create_prescription(request):
    """Create a new prescription profile."""
    form = forms.PrescriptionCreationForm()
    if request.method == 'POST':
        form = forms.PrescriptionCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    return render(
        request,
        'profiles/create_profile.html',
        {'form': form, 'creation_name': 'Prescription'})


@login_required
def edit_prescription_profile(request, pk):
    """Edit a prescription profile."""
    prescription = models.Prescription.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.PrescriptionUpdateForm(
            request.POST,
            instance=prescription
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:prescription_profile',
                                                args=[prescription.id]))
    else:
        form = forms.PrescriptionUpdateForm(instance=prescription)
    return render(
        request,
        'profiles/edit_profile.html',
        {'form': form, 'edit_name': 'Prescription'}
        )


@login_required
def view_prescription_profile(request, pk):
    """Show the details of a prescription profile."""
    prescription = get_object_or_404(models.Prescription, id=pk)
    return render(
        request,
        'profiles/view_prescription_profile.html',
        {'prescription': prescription}
        )

##############################################
# Body weight creation, editing, and viewing #
##############################################
@login_required
def create_new_bodyweight(request, client_id):
    """Create a new bodyweight record."""
    form = forms.NewBodyWeightForm()
    client = get_object_or_404(models.Client, id=client_id)
    if request.method == 'POST':
        form = forms.NewBodyWeightForm(request.POST)
        if form.is_valid():
            weight = form.cleaned_data['weight']
            bodyweight = models.BodyWeight(client=client, weight=weight)
            bodyweight.save()
            return HttpResponseRedirect(reverse('profiles:client_list'))
    return render(
        request,
        'profiles/create_profile.html',
        {'form': form, 'creation_name': 'Bodyweight'})


@login_required
def view_bodyweight_list(request, client_id):
    """List of all measured bodyweights."""
    bodyweights = models.BodyWeight.objects.filter(client_id=client_id)
    return render(request, 'profiles/bodyweight_list.html', {'bodyweights': bodyweights})

care_home_app/profiles/templates/profiles/bodyweight_list.html
{% extends 'layout.html' %}

{% block title %}Bodyweight List{% endblock %}

{% block content %}
  <ul>
  {% for bodyweight in bodyweights %}
    <li>{{ bodyweight.weight }} {{ bodyweight.date }}</li>
  {% endfor %}
  </ul>
{% endblock %}

care_home_app/profiles/templates/profiles/client_list.html
{% extends 'layout.html' %}

{% block title %}Client List{% endblock %}

{% block content %}
  <div class="client-grid">
    <ul>
      {% for client in clients %}
        <li>
          <a href="{% url 'profiles:client_profile' pk=client.id %}">
            <div class="card" style="background-image: url({{ client.portrait.url }});">
              <div class="card-content">
                <h2 class="card-title">{{ client }}</h2>
              </div>
            </div>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

care_home_app/profiles/templates/profiles/create_medication.html
{% extends 'layout.html' %}

{% block title %}Create Medication{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="saveBtn" type="submit">Create</button>
  </form>
{% endblock %}

care_home_app/profiles/templates/profiles/create_profile.html
{% extends 'layout.html' %}

{% block title %}Create {{ creation_name }} Profile{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="saveBtn" type="submit">Create</button>
  </form>
{% endblock %}

care_home_app/profiles/templates/profiles/doctor_list.html
{% extends 'layout.html' %}

{% block title %}Doctor List{% endblock %}

{% block content %}
  <ul>
  {% for doctor in doctors %}
    <li><a href="{% url 'profiles:doctor_profile' pk=doctor.id %}">{{ doctor.first_name }} {{ doctor.last_name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

care_home_app/profiles/templates/profiles/edit_client_profile.html
{% extends 'layout.html' %}

{% block title %}Edit Client Profile{% endblock %}

{% block content %}
  <h1>Edit the client's profile</h1>
  <img src="{{ client.portrait.url }}">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="saveBtn" type="submit">Save</button>
  </form>
{% endblock %}

care_home_app/profiles/templates/profiles/edit_profile.html
{% extends 'layout.html' %}

{% block title %}Edit {{ edit_name }} Profile{% endblock %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="saveBtn" type="submit">Save</button>
  </form>
{% endblock %}

care_home_app/profiles/templates/profiles/medication_list.html
{% extends 'layout.html' %}

{% block title %}Doctor List{% endblock %}

{% block content %}
  <ul>
  {% for medication in medications %}
    <li><a href="{% url 'profiles:medication_profile' pk=medication.id %}">{{ medication }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

care_home_app/profiles/templates/profiles/view_client_profile.html
{% extends 'layout.html' %}

{% block title %}Client Profile{% endblock %}

{% block content %}
  <h1>{{ client.first_name }} {{ client.middle_name }} {{ client.last_name }}</h1>
  <img src="{{ client.portrait.url }}">

  {% if client.dob %}
  <h3>Date of Birth</h3>
  <p>{{ client.dob }}</p>
  {% endif %}
  {% if client.admission_date %}
  <h3>Admission Date</h3>
  <p>{{ client.admission_date }}</p>
  {% endif %}
  {% if client.address %}
  <h3>Address</h3>
  <p>{{ client.address }}</p>
  {% endif %}
  <h3>Weight</h3>
  <p>{{ weight }} lbs.</p>
  <p><a href="{% url 'profiles:create_new_bodyweight' client_id=client.id %}">+ Record Bodyweight</a></p>
  <p><a href="{% url 'profiles:bodyweight_list' client_id=client.id %}">View History</a></p>
  <h3>Doctors</h3>
    {% for doctor in doctors %}
      <p><a href="{% url 'profiles:doctor_profile' pk=doctor.id %}">{{ doctor }}—{{ doctor.specialty }}</a></p>
    {% endfor %}
  <h3>Medications</h3>
    {% for prescription in prescriptions %}
      <p><a href="{% url 'profiles:prescription_profile' pk=prescription.id %}">{{ prescription.medication }}</a></p>
    {% endfor %}
  <hr>
  <p><a href="{% url 'profiles:create_prescription' %}">+ Add New Prescription</a></p>
  <br>
  <p><a href="{% url 'pdf_filler:fill_LIC624' client_pk=client.id %}">Generate new SIR(LIC624)</a></p>
  <p><a href="{% url 'profiles:edit_client_profile' pk=client.id %}">Edit Profile</a></p>
{% endblock %}

care_home_app/profiles/templates/profiles/view_doctor_profile.html
{% extends 'layout.html' %}

{% block title %}Client Profile{% endblock %}

{% block content %}
  <h1>Doctor Profile</h1>
  <h2>{% if doctor.first_name %}{{ doctor.first_name }}{% endif %} {% if doctor.last_name %}{{ doctor.last_name }}{% endif %}{% if doctor.suffix %}, {{ doctor.suffix }}{% endif %}</h2>
  {% if doctor.specialty %}
  <h3>Specialty</h3>
  <p>{{ doctor.specialty }}</p>
  {% endif %}
  {% if doctor.address %}
  <h3>Address</h3>
  <p>{{ doctor.address }}</p>
  {% endif %}
  {% if doctor.phone %}
  <h3>Phone</h3>
  <p>{{ doctor.phone }}</p>
  {% endif %}
  {% if clients %}
  <h3>View client profiles</h3>
    {% for client in clients %}
      <p><a href="{% url 'profiles:client_profile' pk=client.id %}">{{ client }}</a></p>
    {% endfor %}
  {% endif %}
  <p><a href="{% url 'profiles:edit_doctor_profile' pk=doctor.id %}">Edit Profile</a></p>
{% endblock %}

care_home_app/profiles/templates/profiles/view_medication_profile.html
{% extends 'layout.html' %}

{% block title %}Client Profile{% endblock %}

{% block content %}
  <h1>Medication Profile</h1>
  <h2>{{ medication }}</h2>

  <p><a href="{% url 'profiles:edit_medication_profile' pk=medication.id %}">Edit Medication</a></p>
  <p><a href="{% url 'profiles:medication_list' %}">Return to Medication List</a></p>
{% endblock %}

care_home_app/profiles/templates/profiles/view_prescription_profile.html
{% extends 'layout.html' %}

{% block title %}Prescription Profile{% endblock %}

{% block content %}
  <h1>Prescription Profile</h1>
  <h2>Medication Name</h2>
  <p>{{ prescription.medication }}</p>
  <h2>Client</h2>
  <p>{{ prescription.prescribed_to }}</p>
  <h2>Prescribing Doctor</h2>
  <p>{{ prescription.prescribing_dr }}</p>
  <h2>Instructions</h2>
  <p>{{ prescription.rx_instructions }}</p>


  <p><a href="{% url 'profiles:edit_prescription_profile' pk=prescription.id %}">Edit Prescription</a></p>
{% endblock %}